#!/usr/bin/env node
// Single source for every redirect on airfone.app. `node scripts/redirects.mjs`
// writes docs/nginx-redirects.conf. Old URLs had trailing slashes and a
// Nepali root with English under /en/; the new site is English-only with no
// trailing slashes.
import { writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

const SITE = 'https://airfone.app';
const APP = 'https://app.airfone.app';

const AUTH = ['login', 'register', 'forgot-password', 'reset-password', 'verify', 'verify-otp', 'verify-email-otp', 'verify-phone-otp', 'verify-password-reset-otp', 'verify-password-reset-phone'];

/** Old path (exact, as it was served) -> new target. */
export const exact = (() => {
  const m = new Map();
  const both = (old, to) => {
    for (const prefix of ['', '/ne', '/en']) {
      const base = `${prefix}${old}`;
      m.set(base === '' ? '/' : base, to);
      if (base !== '' && !base.endsWith('/')) m.set(`${base}/`, to);
    }
  };
  // Locale roots.
  m.set('/ne', '/'); m.set('/ne/', '/');
  m.set('/en', '/'); m.set('/en/', '/');
  // Pages that still exist under the same name.
  for (const p of ['/pricing', '/contact', '/privacy', '/terms', '/delete-account']) both(p, p);
  // Retired pages.
  for (const p of ['/features', '/platform', '/services']) both(p, '/products/ai-call-agent');
  both('/about', '/contact');
  both('/upcoming', '/');
  both('/waitlist/thanks', '/thanks');
  both('/waitlist', '/demo');
  both('/preview', '/');
  // Sitemap names the old Astro integration wrote.
  m.set('/sitemap-index.xml', '/sitemap.xml');
  m.set('/sitemap-0.xml', '/sitemap.xml');
  for (const p of ['/preview/contact', '/preview/pricing']) both(p, p.replace('/preview', ''));
  // Auth lives in the app.
  for (const a of AUTH) both(`/${a}`, `${APP}/${a}`);
  // The current site's own pages are never redirected to themselves.
  for (const [k, v] of m) if (k === v) m.delete(k);
  return m;
})();

export function nginxConf() {
  const lines = [
    '# Generated by scripts/redirects.mjs. Do not edit by hand.',
    '# Exact old URLs first, then share links, then one rule that drops any',
    '# trailing slash. Every redirect is a single 301 hop.',
    '',
  ];
  for (const [from, to] of exact) lines.push(`location = ${from} { return 301 ${to.startsWith('http') ? to : SITE + to}; }`);
  lines.push('', '# Share links keep their token.');
  lines.push(`location ~ ^/(?:ne/|en/)?share/(.+)$ { return 301 ${APP}/share/$1; }`);
  lines.push('', '# Any other trailing slash: drop it (root excepted).');
  lines.push(`location ~ ^(/.+)/$ { return 301 ${SITE}$1$is_args$args; }`);
  lines.push('', '# Real 404 status for missing pages.', 'error_page 404 /404.html;');
  return `${lines.join('\n')}\n`;
}

/**
 * Cloudflare `_redirects` (the site is served from Cloudflare): exact old URLs
 * first, then the locale prefixes. `/en` and `/ne` were indexed by Google, so
 * every URL under them goes to the same page without the prefix.
 */
export function cloudflareRedirects() {
  const lines = ['# Generated by scripts/redirects.mjs. Do not edit by hand.'];
  for (const [from, to] of exact) lines.push(`${from} ${to} 301`);
  lines.push(`/share/* ${APP}/share/:splat 301`);
  lines.push(`/en/share/* ${APP}/share/:splat 301`);
  lines.push(`/ne/share/* ${APP}/share/:splat 301`);
  lines.push('/en/* /:splat 301');
  lines.push('/ne/* /:splat 301');
  return `${lines.join('\n')}\n`;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  writeFileSync(new URL('../docs/nginx-redirects.conf', import.meta.url), nginxConf());
  writeFileSync(new URL('../public/_redirects', import.meta.url), cloudflareRedirects());
  console.log(`wrote ${exact.size} exact redirects`);
}
